name: Build Rust Binaries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Binaries
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build for ${{ matrix.os }}
        run: |
          cross build --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: poke-${{ matrix.os }}
          path: target/release/
